"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

import os
import sys
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- CONFIGURATION DE PRODUCTION / DÉVELOPPEMENT ---

# DEBUG est désactivé par défaut : en production, oublier une variable ne doit
# jamais exposer les pages d'erreur détaillées. En local, mettre DEBUG=True dans
# le fichier .env (voir .env.example).
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

# Clé secrète : obligatoire hors développement. Une valeur de secours publique
# n'est tolérée qu'en local (DEBUG) et pendant `manage.py test`.
# Vrai pendant `manage.py test` : on y évite le stockage statique de production,
# qui exige un `collectstatic` préalable.
TESTING = 'test' in sys.argv

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG or TESTING:
        SECRET_KEY = 'django-insecure-cle-de-developpement-uniquement'
    else:
        raise ImproperlyConfigured(
            "La variable d'environnement SECRET_KEY est obligatoire quand DEBUG est désactivé."
        )

# Hôtes autorisés : local + sous-domaines Render
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']

# Détection automatique de l'URL spécifique attribuée par Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Sécurité CSRF obligatoire pour les formulaires en HTTPS sur Render
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Indique à Django que Render termine le chiffrement SSL (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'atelier',  # Application principale
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Fichiers statiques servis directement par Python
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- CONFIGURATION DE LA BASE DE DONNÉES (NEON.TECH & LOCAL) ---

if os.environ.get('DATABASE_URL'):
    # Connexion à Neon.tech en production sur Render
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Connexion à PostgreSQL local sous WSL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'atelier_db',
            'USER': 'postgres',
            'PASSWORD': 'admin1234',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }


# --- VALIDATION DES MOTS DE PASSE ---

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- INTERNATIONALISATION ---

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True


# --- FICHIERS STATIQUES (CSS, JS, WHITENOISE) ---

STATIC_URL = '/static/'

STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR] if os.path.exists(STATIC_DIR) else []

# Dossier collectstatic pour le déploiement
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# --- STOCKAGES (CLOUDINARY & WHITENOISE) ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

STORAGES = {
    # Photos et croquis hébergés sur Cloudinary
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    # Fichiers CSS et JS gérés par WhiteNoise (avec gestion de version hashée en prod)
    "staticfiles": {
        "BACKEND": (
            "config.storage.LenientManifestStaticFilesStorage"
            if not (DEBUG or TESTING) else
            "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Configuration Cloudinary (prend en compte CLOUDINARY_URL ou les clés séparées)
if not os.environ.get('CLOUDINARY_URL'):
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    }


# --- EMAILS TRANSACTIONNELS (BREVO) ---

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'b320f3001@smtp-brevo.com'
EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_KEY')
DEFAULT_FROM_EMAIL = 'cohendan13110@gmail.com'


# --- INTELLIGENCE ARTIFICIELLE (GEMINI) ---

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.5-flash')
