# Generated by Django 4.2.30 on 2026-07-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tour_poitrine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_hanches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hauteur_buste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes_morphologie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=200)),
                ('date_commencement', models.DateField()),
                ('date_livraison', models.DateField()),
                ('cout_tissu', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cout_main_doeuvre', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robes', to='atelier.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('est_faite', models.BooleanField(default=False)),
                ('robe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='atelier.robe')),
            ],
        ),
    ]
