# Generated by Django 4.2.30 on 2026-07-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_client_date_naissance_alter_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='robe',
            name='devise',
            field=models.CharField(choices=[('ILS', '₪ (Shekel)'), ('EUR', '€ (Euro)'), ('USD', '$ (Dollar)')], default='ILS', max_length=3, verbose_name='Devise'),
        ),
    ]
