# Generated by Django 4.2.30 on 2026-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0003_robe_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='robe',
            name='croquis',
            field=models.ImageField(blank=True, null=True, upload_to='atelier/croquis/'),
        ),
        migrations.AddField(
            model_name='robe',
            name='photo_tissu',
            field=models.ImageField(blank=True, null=True, upload_to='atelier/tissus/'),
        ),
    ]
