# Generated by Django 4.2.30 on 2026-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0004_robe_croquis_robe_photo_tissu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robe',
            name='photo_tissu',
        ),
        migrations.AddField(
            model_name='robe',
            name='photo_tissus',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='robe',
            name='croquis',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
