# Generated by Django 4.2.30 on 2026-07-12 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0005_remove_robe_photo_tissu_robe_photo_tissus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECETTE', "🟢 Recette (Entrée d'argent)"), ('DEPENSE', "🔴 Dépense (Sortie d'argent)")], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('PAIEMENT_CLIENT', 'Paiement de cliente'), ('TISSU', 'Achat de tissu'), ('FOURNITURES', 'Fournitures (Fils, fermetures, boutons...)'), ('MATERIEL', 'Matériel & Machines (Entretien, achat...)'), ('AUTRE', 'Autre frais / Divers')], max_length=20)),
                ('designation', models.CharField(help_text='Ex: Acompte robe Salome, Achat fils noirs...', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('robe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='atelier.robe')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
