# Generated by Django 4.2.30 on 2026-09-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0007_codereinitialisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_stock', models.CharField(help_text='Identifiant unique étiqueté sur la robe', max_length=50, unique=True, verbose_name='Référence stock (ex: LOC-042)')),
                ('nom_modele', models.CharField(max_length=150, verbose_name='Nom du modèle')),
                ('taille', models.CharField(max_length=20, verbose_name='Taille')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='robes_location/', verbose_name='Photo')),
                ('prix_location_defaut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix standard (€)')),
                ('caution_defaut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Caution standard (€)')),
                ('statut_physique', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NETTOYAGE', 'Au pressing / Nettoyage'), ('REPARATION', 'En réparation / Atelier'), ('HORS_SERVICE', 'Hors service / Retirée')], default='DISPONIBLE', max_length=30, verbose_name='État de disponibilité atelier')),
                ('etat_general', models.TextField(blank=True, verbose_name="État général / Notes d'usure")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robe en location',
                'verbose_name_plural': 'Robes en location',
                'ordering': ['nom_modele', 'reference_stock'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categorie',
            field=models.CharField(choices=[('PAIEMENT_CLIENT', 'Paiement de cliente'), ('LOCATION_ROBE', 'Location de robe'), ('TISSU', 'Achat de tissu'), ('FOURNITURES', 'Fournitures (Fils, fermetures, boutons...)'), ('MATERIEL', 'Matériel & Machines (Entretien, achat...)'), ('AUTRE', 'Autre frais / Divers')], max_length=20),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de retrait prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('date_retour_effectif', models.DateField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('delai_tampon_jours', models.PositiveIntegerField(default=2, help_text="Nombre de jours de blocage après le retour pour l'entretien", verbose_name='Jours de battement (pressing)')),
                ('prix_convenu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de la location (€)')),
                ('caution_montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la caution (€)')),
                ('caution_statut', models.CharField(choices=[('NON_DEPOSEE', 'Non déposée'), ('ENREGISTREE', 'Enregistrée (Chèque / Empreinte)'), ('RESTITUEE', 'Restituée'), ('ENCAISSEE_PARTIEL', 'Retenue partielle'), ('ENCAISSEE_TOTAL', 'Encaissée (Perte / Dégâts)')], default='NON_DEPOSEE', max_length=30, verbose_name='Statut de la caution')),
                ('statut', models.CharField(choices=[('RESERVEE', 'Réservée'), ('EN_COURS', 'En cours (sortie atelier)'), ('TERMINEE', 'Terminée (restituée)'), ('EN_RETARD', 'En retard de restitution'), ('ANNULEE', 'Annulée')], default='RESERVEE', max_length=30, verbose_name='Statut du contrat')),
                ('etat_avant', models.TextField(blank=True, verbose_name="Constat d'état au départ")),
                ('etat_apres', models.TextField(blank=True, verbose_name="Constat d'état au retour")),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Ajustements temporaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='atelier.client', verbose_name='Cliente')),
                ('robe_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='atelier.robelocation', verbose_name='Robe louée')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'verbose_name_plural': 'Contrats de location',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='atelier.location', verbose_name='Location associée'),
        ),
    ]
